#!/usr/bin/env python3

from os import getcwd
from zipfile import ZipFile, is_zipfile
from shutil import make_archive
from typer import Typer

app = Typer()

@app.command()
def zip(name: str, folder: str):

    """ Must be a folder """

    try:
            make_archive(name, 'zip', getcwd(), folder)
            print("\033[92m {} {} \033[00m".format('Compactor successful', getcwd()))

    except MemoryError:
        print("\033[91m {} \033[00m".format('Is out of memory'))

    except Exception:
        print("\033[91m {} \033[00m".format('ERROOOOOOOO'))

@app.command()
def unzip(name: str):

    """ To unzip zip files """
    try:
        if is_zipfile(name):
                with ZipFile(name, 'r') as zip_ref:
                    zip_ref.extractall(getcwd())
                    print("\033[92m {} {} \033[00m".format('Unzip successful: ', getcwd()))
        else:
            print("\033[91m {} \033[00m".format('It is not a zip'))

    except MemoryError:
        print("\033[91m {} \033[00m".format('Is out of memory'))

    except Exception:
        print("\033[91m {} \033[00m".format('ERROOOOOOOO'))
    
if __name__ == "__main__":
    app()